import esbuild from 'esbuild'
import process from 'process'
import { builtinModules } from 'node:module'
import { readFileSync, writeFileSync } from 'fs'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`

const prod = process.argv[2] === 'production'

// Plugin to fix default export for Obsidian
const fixDefaultExport = {
  name: 'fix-default-export',
  setup(build) {
    build.onEnd(() => {
      try {
        let code = readFileSync('main.js', 'utf8')
        
        // Extract the default export class name from the ES module wrapper
        // Pattern 1 (minified): var et={}; ... He(et,{default:()=>F}); ... module.exports=Re(et);
        // Pattern 2 (non-minified): var main_exports = {}; ... __export(main_exports, { default: () => OpenCodeObsidianPlugin }); ... module.exports = __toCommonJS(main_exports);
        let defaultExportName = null
        
        // Try to extract from minified pattern
        const minifiedMatch = code.match(/He\(et,\{default:\(\)=>(F)\}\)/)
        if (minifiedMatch) {
          defaultExportName = minifiedMatch[1]
          // Remove the minified ES module wrapper
          code = code.replace(
            /var et=\{\};[\s\S]*?He\(et,\{default:\(\)=>F\}\);[\s\S]*?module\.exports=Re\(et\);/,
            ''
          )
        } else {
          // Try to extract from non-minified pattern
          const nonMinifiedMatch = code.match(/__export\([^,]+,\s*\{\s*default:\s*\(\)\s*=>\s*(\w+)\s*\}/)
          if (nonMinifiedMatch) {
            defaultExportName = nonMinifiedMatch[1]
            // Remove the non-minified ES module wrapper
            code = code.replace(
              /var main_exports\s*=\s*\{\};[\s\S]*?__export\(main_exports,[\s\S]*?default:\s*\(\)\s*=>\s*\w+[\s\S]*?\}\);[\s\S]*?module\.exports\s*=\s*__toCommonJS\(main_exports\);/,
              ''
            )
          }
        }
        
        // If we couldn't extract from wrapper, find the class that extends Plugin
        if (!defaultExportName) {
          const pluginClassPattern = /((var\s+)?(\w+)\s*=\s*class[\s\S]*?extends[\s\S]*?Plugin[\s\S]*?})\s*;?/g
          let pluginMatch
          let lastMatch = null
          
          // Find the last occurrence (should be the main plugin class)
          while ((pluginMatch = pluginClassPattern.exec(code)) !== null) {
            lastMatch = pluginMatch
          }
          
          if (lastMatch) {
            defaultExportName = lastMatch[3]
          }
        }
        
        if (!defaultExportName) {
          throw new Error('Could not find default export class. The ES module wrapper pattern may have changed.')
        }
        
        // Check if export already exists with the correct name
        const exportPattern = new RegExp(`module\\.exports\\s*=\\s*${defaultExportName}\\s*;`)
        if (exportPattern.test(code)) {
          writeFileSync('main.js', code)
          return
        }
        
        // Remove any existing incorrect module.exports
        code = code.replace(/module\.exports\s*=\s*[^;]+;/g, '')
        
        // Simply add the export at the very end of the file
        // This is the safest approach - the class is already defined, we just need to export it
        code = code.trim()
        if (!code.endsWith(';')) {
          code += ';'
        }
        code += `\nmodule.exports = ${defaultExportName};`
        
        writeFileSync('main.js', code)
      } catch (error) {
        console.error('Error fixing default export:', error)
        throw error
      }
    })
  }
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline', // Keep sourcemap in dev mode for debugging
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  plugins: [fixDefaultExport],
})

if (prod) {
  await context.rebuild()
  process.exit(0)
} else {
  await context.watch()
}
